#!/bin/bash -l
#PBS -l walltime=00:30:00,nodes=1:ppn=1,mem=1gb
#PBS -j oe
#PBS -A PAS0254

cd $HOME/cpu_vah

for((n = 1; n <= $EVENTS; n++))
do
	echo
	echo "Running event $n"
	./cpu_vah $JOBID
	echo
done

cp python/model_parameters/model_parameters_$JOBID.dat tests/auto_grid/train_data/$HYDRO/model_parameters
cp output/fireball_radius/fireball_radius_$JOBID.dat tests/auto_grid/train_data/$HYDRO/fireball_radius
